### ISSUE TITLE
Project name collision

### ISSUE THREAD

**Issue by mortie** [mqnc/json5cpp#1]
Hi! I just saw this repository on https://github.com/json5/json5/wiki/In-The-Wild. I have my own project called Json5Cpp, which is a JSON5 parser (and, soon, serializer) built on top of JsonCpp: https://github.com/mortie/json5cpp/

It's not really a big deal, but it can be a bit confusing that there are two "json5cpp"s. Seeing as mine is older, would you mind renaming this repository? Maybe to something like `cppjson5` or `mqjson5`?

**Comment by mqnc** [comment]
Hey, mortie!
Thanks for reaching out! I see where you're coming from but honestly, given how many "json5" repos are just on that wiki, not to mention all the "jsoncpp" repos out there, I don't see the name collision as a problem. That's why there are user namespaces.
May the better json5cpp get more stars! :)
Best of luck with your project!

**Comment by mortie** [comment]
That's fair, I guess adding the GitHub username is good enough "disambiguation". Disregard this then :)

Take care!
